# Site settings
title: Kyle Morgan - GIS Developer
tag_text: GISDEV-KM
description: gisdev-km.github.io - Solo Theme

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
